### PR TITLE
Uploaded 3 questions

### PR DESCRIPTION
**Pull request by Omm2005**
## What type of PR is this? (check all applicable)

- [x] 🚀 Added Name
- [ ] ✨ Feature
- [x] 🌟 stared the repo
- [ ] 🐛 Grammatical Error
- [x] 📝 Documentation Update
- [x] 🚩 Other

### CODE REVIEW

**Comment by Omm2005** [comment]
Uploaded 3 questions

**Comment by Omm2005** [comment]
Hey I have uploaded 3 questions can look and merge it please

**Comment by Omm2005** [comment]
I have changed the Question to relevant to Programing as you said.

**Comment by Omm2005** [comment]
Also I have added my Name

**Comment by Omm2005** [comment]
@Tc2r1 Please Look into it.

**Comment by Tc2r1** [comment]
@Omm2005  in the languages folder are different folders for different types of quizes, If you want a quiz on kotlin, the kotlin folder will give you questions, if you want a quiz on javascript, the java script folder will give you questions. If you want a quis on data structures, the dsa folder will give you questions. 

Then there is the folder where you have put your questions, That is a template folder used to be copied and pasted for those who wish to add a "coding language" that isn't yet in the repo. 

Please decide on a topic you are familiar with, and make a PR with questions relevant to said topic and placed in that topic's folder. Anything else will be marked as spam and rejected.

**Pull request merged**
