### PR TITLE
Add 3 questions to java

### PR DESCRIPTION
**Pull request by SDtw20**
## Description
🚩Added 3 questions of java

## Add Link of GitHub Profile
[https://github.com/SDtw20]

### CODE REVIEW

**Review by Tc2r1 — CHANGES_REQUESTED** [review]
Please add details to your questions, Explaining why they are true or false. Besides for that this looks good, check out your "issue" again though as I had a question for you.

**Comment by SDtw20** [comment]
Requested changes have been done. You may review

**Review by Tc2r1 — APPROVED** [review]
This looks great! Thanks for your contributions!

**Comment by Tc2r1** [comment]
> Requested changes have been done. You may review

Don't forget to star and add your name to the contributions list :), after the last part (adding name) I will merge. Omega good job.

**Comment by SDtw20** [comment]
> > Requested changes have been done. You may review
> 
> Don't forget to star and add your name to the contributions list :), after the last part (adding name) I will merge. Omega good job.

Done!

**Pull request merged**
